<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container2e5LO9V\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container2e5LO9V/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/Container2e5LO9V.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\Container2e5LO9V\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \Container2e5LO9V\srcDevDebugProjectContainer(array(
    'container.build_hash' => '2e5LO9V',
    'container.build_id' => '041b7b49',
    'container.build_time' => 1531684806,
), __DIR__.\DIRECTORY_SEPARATOR.'Container2e5LO9V');
